
celadon.data = {}

/* -------[ CELADON: ESTADOS ]-------*/

celadon.data.estados = {
  "BA": {
    "Estado": "Bahia",
    "Capital": "Salvador",
    "Pop": 15150143,
    "Prep": "da"
  },
  "PB": {
    "Estado": "Paraíba",
    "Capital": "João Pessoa",
    "Pop": 3950359,
    "Prep": "da"
  },
  "AL": {
    "Estado": "Alagoas",
    "Capital": "Maceió",
    "Pop": 3327551,
    "Prep": "do"
  },
  "GO": {
    "Estado": "Goiás",
    "Capital": "Goiânia",
    "Pop": 6551322,
    "Prep": "de"
  },
  "MS": {
    "Estado": "Mato Grosso do Sul",
    "Capital": "Campo Grande",
    "Pop": 2630098,
    "Prep": "do"
  },
  "MT": {
    "Estado": "Mato Grosso",
    "Capital": "Cuiabá",
    "Pop": 3236578,
    "Prep": "do"
  },
  "MG": {
    "Estado": "Minas Gerais",
    "Capital": "Belo Horizonte",
    "Pop": 20777672,
    "Prep": "de"
  },
  "PE": {
    "Estado": "Pernambuco",
    "Capital": "Recife",
    "Pop": 9297861,
    "Prep": "de"
  },
  "RO": {
    "Estado": "Rondônia",
    "Capital": "Porto Velho",
    "Pop": 1755015,
    "Prep": "de"
  },
  "RR": {
    "Estado": "Roraima",
    "Capital": "Boa Vista",
    "Pop": 500826,
    "Prep": "de"
  },
  "SC": {
    "Estado": "Santa Catarina",
    "Capital": "Florianópolis",
    "Pop": 6734568,
    "Prep": "de"
  },
  "SE": {
    "Estado": "Sergipe",
    "Capital": "Aracaju",
    "Pop": 2227294,
    "Prep": "de"
  },
  "AC": {
    "Estado": "Acre",
    "Capital": "Rio Branco",
    "Pop": 795145,
    "Prep": "do"
  },
  "AP": {
    "Estado": "Amapá",
    "Capital": "Macapá",
    "Pop": 756500,
    "Prep": "do"
  },
  "AM": {
    "Estado": "Amazonas",
    "Capital": "Manaus",
    "Pop": 3893763,
    "Prep": "do"
  },
  "CE": {
    "Estado": "Ceará",
    "Capital": "Fortaleza",
    "Pop": 8867448,
    "Prep": "do"
  },
  "DF": {
    "Estado": "Distrito Federal",
    "Capital": "Brasília",
    "Pop": 2867869,
    "Prep": "do"
  },
  "ES": {
    "Estado": "Espírito Santo",
    "Capital": "Vitória",
    "Pop": 3894899,
    "Prep": "do"
  },
  "SP": {
    "Estado": "São Paulo",
    "Capital": "São Paulo",
    "Pop": 44169350,
    "Prep": "de"
  },
  "RJ": {
    "Estado": "Rio de Janeiro",
    "Capital": "Rio de Janeiro",
    "Pop": 16497395,
    "Prep": "do"
  },
  "MA": {
    "Estado": "Maranhão",
    "Capital": "São Luís",
    "Pop": 6861924,
    "Prep": "do"
  },
  "PR": {
    "Estado": "Paraná",
    "Capital": "Curitiba",
    "Pop": 11112062,
    "Prep": "do"
  },
  "PA": {
    "Estado": "Pará",
    "Capital": "Belém",
    "Pop": 8101180,
    "Prep": "do"
  },
  "PI": {
    "Estado": "Piauí",
    "Capital": "Teresina",
    "Pop": 3198185,
    "Prep": "do"
  },
  "RN": {
    "Estado": "Rio Grande do Norte",
    "Capital": "Natal",
    "Pop": 3419550,
    "Prep": "do"
  },
  "RS": {
    "Estado": "Rio Grande do Sul",
    "Capital": "Porto Alegre",
    "Pop": 11228091,
    "Prep": "do"
  },
  "TO": {
    "Estado": "Tocantins",
    "Capital": "Palmas",
    "Pop": 1502759,
    "Prep": "do"
  }
}

/* -------[ CELADON: SENADORES ]-------*/
celadon.data.senadores = [
  {
    "Nome": "Aécio Neves",
    "ID": 391,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "MG"
  },
  {
    "Nome": "Aloysio Nunes Ferreira",
    "ID": 846,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "SP"
  },
  {
    "Nome": "Alvaro Dias",
    "ID": 945,
    "Partido": "PV",
    "Tratamento": "Pelo PV, Exmo. Sr. Senador",
    "Estado": "PR"
  },
  {
    "Nome": "Ana Amélia",
    "ID": 4988,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exma. Sra. Senadora",
    "Estado": "RS"
  },
  {
    "Nome": "Ângela Portela",
    "ID": 4697,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exma. Sra. Senadora",
    "Estado": "RR"
  },
  {
    "Nome": "Antonio Anastasia",
    "ID": 5529,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "MG"
  },
  {
    "Nome": "Antonio Carlos Valadares",
    "ID": 3,
    "Partido": "PSB",
    "Tratamento": "Pelo PSB, Exmo. Sr. Senador",
    "Estado": "SE"
  },
  {
    "Nome": "Armando Monteiro",
    "ID": 715,
    "Partido": "PTB",
    "Tratamento": "Pelo PTB, Exmo. Sr. Senador",
    "Estado": "PE"
  },
  {
    "Nome": "Ataídes Oliveira",
    "ID": 5164,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "TO"
  },
  {
    "Nome": "Benedito de Lira",
    "ID": 3823,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exmo. Sr. Senador",
    "Estado": "AL"
  },
  {
    "Nome": "Cidinho Santos",
    "ID": 5108,
    "Partido": "PR",
    "Tratamento": "Pelo PR, Exmo. Sr. Senador",
    "Estado": "MT"
  },
  {
    "Nome": "Ciro Nogueira",
    "ID": 739,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exmo. Sr. Senador",
    "Estado": "PI"
  },
  {
    "Nome": "Cristovam Buarque",
    "ID": 3398,
    "Partido": "PPS",
    "Tratamento": "Pelo PPS, Exmo. Sr. Senador",
    "Estado": "DF"
  },
  {
    "Nome": "Dalirio Beber",
    "ID": 5132,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "SC"
  },
  {
    "Nome": "Dário Berger",
    "ID": 5537,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "SC"
  },
  {
    "Nome": "Davi Alcolumbre",
    "ID": 3830,
    "Partido": "DEM",
    "Tratamento": "Pelo DEM, Exmo. Sr. Senador",
    "Estado": "AP"
  },
  {
    "Nome": "Deca",
    "ID": 5199,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "PB"
  },
  {
    "Nome": "Edison Lobão",
    "ID": 16,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "MA"
  },
  {
    "Nome": "Eduardo Amorim",
    "ID": 4721,
    "Partido": "PSC",
    "Tratamento": "Pelo PSC, Exmo. Sr. Senador",
    "Estado": "SE"
  },
  {
    "Nome": "Eduardo Braga",
    "ID": 4994,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "AM"
  },
  {
    "Nome": "Elmano Férrer",
    "ID": 5531,
    "Partido": "PTB",
    "Tratamento": "Pelo PTB, Exmo. Sr. Senador",
    "Estado": "PI"
  },
  {
    "Nome": "Eunício Oliveira",
    "ID": 612,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "CE"
  },
  {
    "Nome": "Fátima Bezerra",
    "ID": 3713,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exma. Sra. Senadora",
    "Estado": "RN"
  },
  {
    "Nome": "Fernando Bezerra Coelho",
    "ID": 5540,
    "Partido": "PSB",
    "Tratamento": "Pelo PSB, Exmo. Sr. Senador",
    "Estado": "PE"
  },
  {
    "Nome": "Fernando Collor",
    "ID": 4525,
    "Partido": "PTC",
    "Tratamento": "Pelo PTC, Exmo. Sr. Senador",
    "Estado": "AL"
  },
  {
    "Nome": "Flexa Ribeiro",
    "ID": 3634,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "PA"
  },
  {
    "Nome": "Garibaldi Alves Filho",
    "ID": 87,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "RN"
  },
  {
    "Nome": "Gladson Cameli",
    "ID": 4558,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exmo. Sr. Senador",
    "Estado": "AC"
  },
  {
    "Nome": "Gleisi Hoffmann",
    "ID": 5006,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exma. Sra. Senadora",
    "Estado": "PR"
  },
  {
    "Nome": "Hélio José",
    "ID": 5100,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "DF"
  },
  {
    "Nome": "Humberto Costa",
    "ID": 5008,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exmo. Sr. Senador",
    "Estado": "PE"
  },
  {
    "Nome": "Ivo Cassol",
    "ID": 5004,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exmo. Sr. Senador",
    "Estado": "RO"
  },
  {
    "Nome": "Jader Barbalho",
    "ID": 35,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "PA"
  },
  {
    "Nome": "João Alberto Souza",
    "ID": 950,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "MA"
  },
  {
    "Nome": "João Capiberibe",
    "ID": 3394,
    "Partido": "PSB",
    "Tratamento": "Pelo PSB, Exmo. Sr. Senador",
    "Estado": "AP"
  },
  {
    "Nome": "Jorge Viana",
    "ID": 4990,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exmo. Sr. Senador",
    "Estado": "AC"
  },
  {
    "Nome": "José Agripino",
    "ID": 40,
    "Partido": "DEM",
    "Tratamento": "Pelo DEM, Exmo. Sr. Senador",
    "Estado": "RN"
  },
  {
    "Nome": "José Aníbal",
    "ID": 878,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "SP"
  },
  {
    "Nome": "José Maranhão",
    "ID": 3361,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "PB"
  },
  {
    "Nome": "José Medeiros",
    "ID": 5112,
    "Partido": "PSD",
    "Tratamento": "Pelo PSD, Exmo. Sr. Senador",
    "Estado": "MT"
  },
  {
    "Nome": "José Pimentel",
    "ID": 615,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exmo. Sr. Senador",
    "Estado": "CE"
  },
  {
    "Nome": "Kátia Abreu",
    "ID": 1249,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exma. Sra. Senadora",
    "Estado": "TO"
  },
  {
    "Nome": "Lasier Martins",
    "ID": 5533,
    "Partido": "PDT",
    "Tratamento": "Pelo PDT, Exmo. Sr. Senador",
    "Estado": "RS"
  },
  {
    "Nome": "Lídice da Mata",
    "ID": 4575,
    "Partido": "PSB",
    "Tratamento": "Pelo PSB, Exmoa. Sra. Senadora",
    "Estado": "BA"
  },
  {
    "Nome": "Lindbergh Farias",
    "ID": 3695,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exmo. Sr. Senador",
    "Estado": "RJ"
  },
  {
    "Nome": "Lúcia Vânia",
    "ID": 643,
    "Partido": "PSB",
    "Tratamento": "Pelo PSD, Exma. Sra. Senadora",
    "Estado": "GO"
  },
  {
    "Nome": "Magno Malta",
    "ID": 631,
    "Partido": "PR",
    "Tratamento": "Pelo PR, Exmo. Sr. Senador",
    "Estado": "ES"
  },
  {
    "Nome": "Marcelo Crivella",
    "ID": 3366,
    "Partido": "PRB",
    "Tratamento": "Pelo PRB, Exmo. Sr. Senador",
    "Estado": "RJ"
  },
  {
    "Nome": "Marta Suplicy",
    "ID": 5000,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exma. Sra. Senadora",
    "Estado": "SP"
  },
  {
    "Nome": "Omar Aziz",
    "ID": 5525,
    "Partido": "PSD",
    "Tratamento": "Pelo PSD, Exmo. Sr. Senador",
    "Estado": "AM"
  },
  {
    "Nome": "Otto Alencar",
    "ID": 5523,
    "Partido": "PSD",
    "Tratamento": "Pelo PSD, Exmo. Sr. Senador",
    "Estado": "BA"
  },
  {
    "Nome": "Pastor Valadares",
    "ID": 5617,
    "Partido": "PDT",
    "Tratamento": "Pelo PDT, Exmo. Sr. Senador",
    "Estado": "RO"
  },
  {
    "Nome": "Paulo Bauer",
    "ID": 3741,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "SC"
  },
  {
    "Nome": "Paulo Paim",
    "ID": 825,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exmo. Sr. Senador",
    "Estado": "RS"
  },
  {
    "Nome": "Paulo Rocha",
    "ID": 374,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exmo. Sr. Senador",
    "Estado": "PA"
  },
  {
    "Nome": "Pedro Chaves",
    "ID": 5116,
    "Partido": "PSC",
    "Tratamento": "Pelo PSC, Exmo. Sr. Senador",
    "Estado": "MS"
  },
  {
    "Nome": "Pinto Itamaraty",
    "ID": 4606,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "MA"
  },
  {
    "Nome": "Raimundo Lira",
    "ID": 2207,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "PB"
  },
  {
    "Nome": "Randolfe Rodrigues",
    "ID": 5012,
    "Partido": "REDE",
    "Tratamento": "Pela REDE, Exmo. Sr. Senador",
    "Estado": "AP"
  },
  {
    "Nome": "Regina Sousa",
    "ID": 5182,
    "Partido": "PT",
    "Tratamento": "Pelo PT, Exma. Sra. Senadora",
    "Estado": "PI"
  },
  {
    "Nome": "Reguffe",
    "ID": 5236,
    "Partido": "S/Partido",
    "Tratamento": "Sem partido, Exmo. Sr. Senador",
    "Estado": "DF"
  },
  {
    "Nome": "Renan Calheiros",
    "ID": 70,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "AL"
  },
  {
    "Nome": "Ricardo Ferraço",
    "ID": 635,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "ES"
  },
  {
    "Nome": "Roberto Muniz",
    "ID": 5052,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exmo. Sr. Senador",
    "Estado": "BA"
  },
  {
    "Nome": "Roberto Requião",
    "ID": 72,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "PR"
  },
  {
    "Nome": "Romário",
    "ID": 5322,
    "Partido": "PSB",
    "Tratamento": "Pelo PSD, Exmo. Sr. Senador",
    "Estado": "RJ"
  },
  {
    "Nome": "Romero Jucá",
    "ID": 73,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "RR"
  },
  {
    "Nome": "Ronaldo Caiado",
    "ID": 456,
    "Partido": "DEM",
    "Tratamento": "Pelo DEM, Exmo. Sr. Senador",
    "Estado": "GO"
  },
  {
    "Nome": "Rose de Freitas",
    "ID": 2331,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exma. Sra. Senadora",
    "Estado": "ES"
  },
  {
    "Nome": "Sérgio Petecão",
    "ID": 4560,
    "Partido": "PSD",
    "Tratamento": "Pelo PSD, Exmo. Sr. Senador",
    "Estado": "AC"
  },
  {
    "Nome": "Simone Tebet",
    "ID": 5527,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exma. Sra. Senadora",
    "Estado": "MS"
  },
  {
    "Nome": "Tasso Jereissati",
    "ID": 3396,
    "Partido": "PSDB",
    "Tratamento": "Pelo PSDB, Exmo. Sr. Senador",
    "Estado": "CE"
  },
  {
    "Nome": "Telmário Mota",
    "ID": 5535,
    "Partido": "PDT",
    "Tratamento": "Pelo PDT, Exmo. Sr. Senador",
    "Estado": "RR"
  },
  {
    "Nome": "Valdir Raupp",
    "ID": 3372,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "RO"
  },
  {
    "Nome": "Vanessa Grazziotin",
    "ID": 558,
    "Partido": "PCdoB",
    "Tratamento": "Pelo PCdoB, Exma. Sra. Senadora",
    "Estado": "AM"
  },
  {
    "Nome": "Vicentinho Alves",
    "ID": 4763,
    "Partido": "PR",
    "Tratamento": "Pelo PR, Exmo. Sr. Senador",
    "Estado": "TO"
  },
  {
    "Nome": "Virginio de Carvalho",
    "ID": 4786,
    "Partido": "PSC",
    "Tratamento": "Pelo PSC, Exmo. Sr. Senador",
    "Estado": "SE"
  },
  {
    "Nome": "Waldemir Moka",
    "ID": 1176,
    "Partido": "PMDB",
    "Tratamento": "Pelo PMDB, Exmo. Sr. Senador",
    "Estado": "MS"
  },
  {
    "Nome": "Wellington Fagundes",
    "ID": 1173,
    "Partido": "PR",
    "Tratamento": "Pelo PR, Exmo. Sr. Senador",
    "Estado": "MT"
  },
  {
    "Nome": "Wilder Morais",
    "ID": 5070,
    "Partido": "PP",
    "Tratamento": "Pelo PP, Exmo. Sr. Senador",
    "Estado": "GO"
  },
  {
    "Nome": "Zeze Perrella",
    "ID": 5144,
    "Partido": "PTB",
    "Tratamento": "Pelo PTB, Exmo. Sr. Senador",
    "Estado": "MG"
  }
]


celadon.data.referenciaDeGastos = {
    "Aluguel de imoveis para escritorio politico": "Aluguel de imóveis para escritório político",
    "Aquisicao de material de consumo": "Aquisição de material de consumo",
    "Locomocao. hospedagem. alimentacao. combustiveis e": "Locomoção, hospedagem, alimentação e combustível",
    "Contratacao de servicos de apoio ao parlamentar": "Apoio parlamentar",
    "Divulgacao da atividade parlamentar": "Divulgação da atividade parlamentar",
    "Passagens aereas. aquaticas e terrestres nacionais": "Passagens aérias, aquáticas e terrestres",
    "Servicos de Seguranca Privada": "Segurança Privada",
    "Diarias":"Diárias",
    "Ressarcimento de Passagens":"Ressarcimento de Passagens",
    "Combustiveis": "Combustíveis",
    "Outros materiais": "Outros materiais",
    "Correios": "Despesas de Correios"
}

celadon.data.gastos = {
  "Aécio Neves": {
    "ID": 391,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 186758.27,
    "Aquisicao de material de consumo": 12539.66,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 7163.69,
    "Contratacao de servicos de apoio ao parlamentar": 2175.7,
    "Divulgacao da atividade parlamentar": 7424.6,
    "Passagens aereas. aquaticas e terrestres nacionais": 34086.46,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 768.27,
    "Outros materiais": 4067.45,
    "Correios": 39999.26
  },
  "Aloysio Nunes Ferreira": {
    "ID": 846,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 117410.57,
    "Aquisicao de material de consumo": 25771.43,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 13270.48,
    "Contratacao de servicos de apoio ao parlamentar": 5725.8,
    "Divulgacao da atividade parlamentar": 1467.52,
    "Passagens aereas. aquaticas e terrestres nacionais": 60017.76,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 14626.56,
    "Ressarcimento de Passagens": 10809.39,
    "Combustiveis": 4414.3,
    "Outros materiais": 3388.83,
    "Correios": 27695.32
  },
  "Alvaro Dias": {
    "ID": 945,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 8139.3,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 118275.74,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 10452.86,
    "Outros materiais": 5391.1,
    "Correios": 16339.12
  },
  "Ana Amélia": {
    "ID": 4988,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 22495.6,
    "Aquisicao de material de consumo": 4289.86,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 24317.45,
    "Contratacao de servicos de apoio ao parlamentar": 20700,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 69032.06,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 12361.11,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 7489.66,
    "Outros materiais": 2942.29,
    "Correios": 31231.43
  },
  "Ângela Portela": {
    "ID": 4697,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 25735.21,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 37635.06,
    "Contratacao de servicos de apoio ao parlamentar": 169500,
    "Divulgacao da atividade parlamentar": 73023.6,
    "Passagens aereas. aquaticas e terrestres nacionais": 48772.99,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 9459.84,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6526.91,
    "Outros materiais": 2932.14,
    "Correios": 61798.36
  },
  "Antonio Anastasia": {
    "ID": 5529,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 112378.76,
    "Aquisicao de material de consumo": 27276.44,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 4330.66,
    "Contratacao de servicos de apoio ao parlamentar": 65346.8,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 75628.89,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 15699.21,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4541.18,
    "Outros materiais": 4329.6,
    "Correios": 13341.71
  },
  "Antonio Carlos Valadares": {
    "ID": 3,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 5225,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 48814.22,
    "Contratacao de servicos de apoio ao parlamentar": 29900,
    "Divulgacao da atividade parlamentar": 41400,
    "Passagens aereas. aquaticas e terrestres nacionais": 36224.88,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 27265.72,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5600.84,
    "Outros materiais": 3505.57,
    "Correios": 11540.58
  },
  "Armando Monteiro": {
    "ID": 715,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 29945.23,
    "Aquisicao de material de consumo": 5807.15,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 4923.33,
    "Contratacao de servicos de apoio ao parlamentar": 10457.5,
    "Divulgacao da atividade parlamentar": 14840,
    "Passagens aereas. aquaticas e terrestres nacionais": 55552.35,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 1932.79,
    "Outros materiais": 3021.96,
    "Correios": 16127.13
  },
  "Ataídes Oliveira": {
    "ID": 5164,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 578.94,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 36964,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 158054.68,
    "Passagens aereas. aquaticas e terrestres nacionais": 80038.1,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 9769.39,
    "Outros materiais": 2512.42,
    "Correios": 19482.83
  },
  "Benedito de Lira": {
    "ID": 3823,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 64980.07,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 12989.57,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 12394.72,
    "Passagens aereas. aquaticas e terrestres nacionais": 66476.59,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6571.84,
    "Outros materiais": 1182.19,
    "Correios": 723.1
  },
  "Cidinho Santos": {
    "ID": 5108,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 45082.97,
    "Aquisicao de material de consumo": 39148.8,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 9800,
    "Divulgacao da atividade parlamentar": 45600,
    "Passagens aereas. aquaticas e terrestres nacionais": 29659.6,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 31423.81,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3890.06,
    "Outros materiais": 2300.61,
    "Correios": 545.29
  },
  "Ciro Nogueira": {
    "ID": 739,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 1188,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 229861.22,
    "Contratacao de servicos de apoio ao parlamentar": 70000,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 38418.21,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 16481.92,
    "Ressarcimento de Passagens": 90104.8,
    "Combustiveis": 9763.28,
    "Outros materiais": 4098.39,
    "Correios": 48316.35
  },
  "Cristovam Buarque": {
    "ID": 3398,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 60000,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 0,
    "Outros materiais": 4354.4,
    "Correios": 11533.44
  },
  "Dalirio Beber": {
    "ID": 5132,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 39499.62,
    "Aquisicao de material de consumo": 18927.11,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 65856.66,
    "Contratacao de servicos de apoio ao parlamentar": 153.35,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 51557.21,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 7645.94,
    "Outros materiais": 3106.98,
    "Correios": 51618.3
  },
  "Dário Berger": {
    "ID": 5537,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 36742.99,
    "Aquisicao de material de consumo": 23508.61,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 83936.78,
    "Contratacao de servicos de apoio ao parlamentar": 46417.26,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 76247.75,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6335.9,
    "Outros materiais": 4210.04,
    "Correios": 14992.94
  },
  "Davi Alcolumbre": {
    "ID": 3830,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 36286.87,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 92317.5,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 588.6,
    "Passagens aereas. aquaticas e terrestres nacionais": 16068.81,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 680.45,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6915.96,
    "Outros materiais": 1643.48,
    "Correios": 26337.78
  },
  "Deca": {
    "ID": 5199,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 1063.17,
    "Aquisicao de material de consumo": 122.99,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 8710.52,
    "Contratacao de servicos de apoio ao parlamentar": 2070,
    "Divulgacao da atividade parlamentar": 32800,
    "Passagens aereas. aquaticas e terrestres nacionais": 12545,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 630.15,
    "Outros materiais": 859.04,
    "Correios": 16941.67
  },
  "Edison Lobão": {
    "ID": 16,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 110586.18,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 3514.19,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 10360.43,
    "Outros materiais": 4666.71,
    "Correios": 15433.64
  },
  "Eduardo Amorim": {
    "ID": 4721,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 45621.24,
    "Aquisicao de material de consumo": 16763,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 94198.02,
    "Contratacao de servicos de apoio ao parlamentar": 4000,
    "Divulgacao da atividade parlamentar": 3200,
    "Passagens aereas. aquaticas e terrestres nacionais": 90296.65,
    "Servicos de Seguranca Privada": 1900.56,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5406.39,
    "Outros materiais": 3958.98,
    "Correios": 11530.36
  },
  "Eduardo Braga": {
    "ID": 4994,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 360,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 30,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 156488,
    "Passagens aereas. aquaticas e terrestres nacionais": 96788.6,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3861.48,
    "Outros materiais": 2781.4,
    "Correios": 1257.43
  },
  "Elmano Férrer": {
    "ID": 5531,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 70315.4,
    "Aquisicao de material de consumo": 11528.34,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 83677.22,
    "Contratacao de servicos de apoio ao parlamentar": 60912,
    "Divulgacao da atividade parlamentar": 57500,
    "Passagens aereas. aquaticas e terrestres nacionais": 71437.66,
    "Servicos de Seguranca Privada": 3345.86,
    "Diarias": 680.45,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 7827.95,
    "Outros materiais": 1711.12,
    "Correios": 25768.22
  },
  "Eunício Oliveira": {
    "ID": 612,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2765.9,
    "Outros materiais": 4144.92,
    "Correios": 14120.18
  },
  "Fátima Bezerra": {
    "ID": 3713,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 71848.55,
    "Aquisicao de material de consumo": 9761.65,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 32880.28,
    "Contratacao de servicos de apoio ao parlamentar": 17336,
    "Divulgacao da atividade parlamentar": 35350,
    "Passagens aereas. aquaticas e terrestres nacionais": 110978.93,
    "Servicos de Seguranca Privada": 5200,
    "Diarias": 17318.18,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2239.01,
    "Outros materiais": 2628.69,
    "Correios": 2010.87
  },
  "Fernando Bezerra Coelho": {
    "ID": 5540,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 63845.96,
    "Aquisicao de material de consumo": 9524.99,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 155034.9,
    "Contratacao de servicos de apoio ao parlamentar": 45639,
    "Divulgacao da atividade parlamentar": 10155,
    "Passagens aereas. aquaticas e terrestres nacionais": 89813.44,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 9609.6,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4184.43,
    "Outros materiais": 4149.39,
    "Correios": 41621.69
  },
  "Fernando Collor": {
    "ID": 4525,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 96000,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 286815.94,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2885.27,
    "Outros materiais": 3569.53,
    "Correios": 107879.87
  },
  "Flexa Ribeiro": {
    "ID": 3634,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 57737.91,
    "Aquisicao de material de consumo": 18248.3,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 148097.53,
    "Contratacao de servicos de apoio ao parlamentar": 3077.9,
    "Divulgacao da atividade parlamentar": 2000,
    "Passagens aereas. aquaticas e terrestres nacionais": 46181.11,
    "Servicos de Seguranca Privada": 10258.34,
    "Diarias": 680.45,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 9516.34,
    "Outros materiais": 3658.5,
    "Correios": 4291.56
  },
  "Garibaldi Alves Filho": {
    "ID": 87,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 45584.07,
    "Aquisicao de material de consumo": 9810.04,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 39039.33,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 14500,
    "Passagens aereas. aquaticas e terrestres nacionais": 65204.01,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6283.24,
    "Outros materiais": 3975.71,
    "Correios": 2704.44
  },
  "Gladson Cameli": {
    "ID": 4558,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 16422,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 123116.01,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 125707.23,
    "Passagens aereas. aquaticas e terrestres nacionais": 93387.73,
    "Servicos de Seguranca Privada": 5802.74,
    "Diarias": 24476.19,
    "Ressarcimento de Passagens": 27536.78,
    "Combustiveis": 6912.33,
    "Outros materiais": 3204.86,
    "Correios": 17245.38
  },
  "Gleisi Hoffmann": {
    "ID": 5006,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 58700.33,
    "Aquisicao de material de consumo": 22220.5,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 27396.89,
    "Contratacao de servicos de apoio ao parlamentar": 80272.77,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 77645.81,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 26103.34,
    "Ressarcimento de Passagens": 1513.77,
    "Combustiveis": 7358.28,
    "Outros materiais": 3580.63,
    "Correios": 18827.46
  },
  "Hélio José": {
    "ID": 5100,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 66432.11,
    "Aquisicao de material de consumo": 20826.29,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 53920,
    "Divulgacao da atividade parlamentar": 3202.6,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 25394.56,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 8574.19,
    "Outros materiais": 5301.21,
    "Correios": 6329.24
  },
  "Humberto Costa": {
    "ID": 5008,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 79864.04,
    "Aquisicao de material de consumo": 16957.65,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 155180.77,
    "Contratacao de servicos de apoio ao parlamentar": 4572.14,
    "Divulgacao da atividade parlamentar": 11000,
    "Passagens aereas. aquaticas e terrestres nacionais": 101290.99,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 34339.73,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6538.46,
    "Outros materiais": 2942.44,
    "Correios": 113163.38
  },
  "Ivo Cassol": {
    "ID": 5004,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 26358.18,
    "Aquisicao de material de consumo": 872.73,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 176211.88,
    "Contratacao de servicos de apoio ao parlamentar": 100,
    "Divulgacao da atividade parlamentar": 75850,
    "Passagens aereas. aquaticas e terrestres nacionais": 63831.51,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4082.1,
    "Outros materiais": 2540.36,
    "Correios": 9863.81
  },
  "Jader Barbalho": {
    "ID": 35,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 50000,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 160128.53,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 0,
    "Outros materiais": 3759.05,
    "Correios": 10528.56
  },
  "João Alberto Souza": {
    "ID": 950,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 19746.64,
    "Aquisicao de material de consumo": 800,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 94501.2,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 40699.92,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5567.57,
    "Outros materiais": 4432.27,
    "Correios": 60905.64
  },
  "João Capiberibe": {
    "ID": 3394,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 60529.96,
    "Aquisicao de material de consumo": 57985.9,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 136382.47,
    "Contratacao de servicos de apoio ao parlamentar": 7000,
    "Divulgacao da atividade parlamentar": 82000,
    "Passagens aereas. aquaticas e terrestres nacionais": 78610.98,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 0,
    "Outros materiais": 2967.06,
    "Correios": 16659.63
  },
  "Jorge Viana": {
    "ID": 4990,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 67876.6,
    "Aquisicao de material de consumo": 27022.75,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 103229.81,
    "Contratacao de servicos de apoio ao parlamentar": 7774.11,
    "Divulgacao da atividade parlamentar": 10000,
    "Passagens aereas. aquaticas e terrestres nacionais": 108564.16,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 20167.68,
    "Ressarcimento de Passagens": 9280.28,
    "Combustiveis": 4805.73,
    "Outros materiais": 3148.85,
    "Correios": 47513.21
  },
  "José Agripino": {
    "ID": 40,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 20056.36,
    "Aquisicao de material de consumo": 156.35,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 109266.8,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 6120,
    "Passagens aereas. aquaticas e terrestres nacionais": 62254.01,
    "Servicos de Seguranca Privada": 43191.1,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 9541.47,
    "Outros materiais": 4574.28,
    "Correios": 41370.19
  },
  "José Aníbal": {
    "ID": 878,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 76952.83,
    "Aquisicao de material de consumo": 9206.25,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 17131.15,
    "Contratacao de servicos de apoio ao parlamentar": 24326.69,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 48059.62,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 1912.68,
    "Outros materiais": 2167.46,
    "Correios": 1169.32
  },
  "José Maranhão": {
    "ID": 3361,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 9923.05,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 42726.98,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 87000,
    "Passagens aereas. aquaticas e terrestres nacionais": 46605.78,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3326.12,
    "Outros materiais": 3861.48,
    "Correios": 72357.14
  },
  "José Medeiros": {
    "ID": 5112,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 60332.54,
    "Aquisicao de material de consumo": 4814.89,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 112971.35,
    "Contratacao de servicos de apoio ao parlamentar": 2749.98,
    "Divulgacao da atividade parlamentar": 104538,
    "Passagens aereas. aquaticas e terrestres nacionais": 97651.19,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 12040.73,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5045.79,
    "Outros materiais": 3949.46,
    "Correios": 6626.6
  },
  "José Pimentel": {
    "ID": 615,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 36268.52,
    "Aquisicao de material de consumo": 43196.41,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 102178.68,
    "Contratacao de servicos de apoio ao parlamentar": 41759.29,
    "Divulgacao da atividade parlamentar": 1000,
    "Passagens aereas. aquaticas e terrestres nacionais": 89105.29,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2199.98,
    "Outros materiais": 2243.36,
    "Correios": 48214.33
  },
  "Kátia Abreu": {
    "ID": 1249,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 40252.96,
    "Aquisicao de material de consumo": 5700,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 8680.94,
    "Contratacao de servicos de apoio ao parlamentar": 85,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 13091.69,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 11215.36,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4869.64,
    "Outros materiais": 4961.01,
    "Correios": 11836.59
  },
  "Lasier Martins": {
    "ID": 5533,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 56489.86,
    "Aquisicao de material de consumo": 7613.77,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 53201.86,
    "Contratacao de servicos de apoio ao parlamentar": 9313.4,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 87639.15,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 5289,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4684.77,
    "Outros materiais": 2888.74,
    "Correios": 6706.58
  },
  "Lídice da Mata": {
    "ID": 4575,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 95209.77,
    "Aquisicao de material de consumo": 20643.16,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 38758.31,
    "Contratacao de servicos de apoio ao parlamentar": 16010,
    "Divulgacao da atividade parlamentar": 3740,
    "Passagens aereas. aquaticas e terrestres nacionais": 58692.76,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 40506.49,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5847.25,
    "Outros materiais": 2457.35,
    "Correios": 36411.25
  },
  "Lindbergh Farias": {
    "ID": 3695,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 67461.5,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 896,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 271188.11,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 32952.09,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6293.41,
    "Outros materiais": 2861.1,
    "Correios": 1691.57
  },
  "Lúcia Vânia": {
    "ID": 643,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 16065.93,
    "Aquisicao de material de consumo": 4776.9,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 120684.74,
    "Contratacao de servicos de apoio ao parlamentar": 14869,
    "Divulgacao da atividade parlamentar": 63405.5,
    "Passagens aereas. aquaticas e terrestres nacionais": 12380.88,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6387.63,
    "Outros materiais": 2946.01,
    "Correios": 7531.69
  },
  "Magno Malta": {
    "ID": 631,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 35803.94,
    "Aquisicao de material de consumo": 1520.9,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 52857.49,
    "Contratacao de servicos de apoio ao parlamentar": 11520,
    "Divulgacao da atividade parlamentar": 26740,
    "Passagens aereas. aquaticas e terrestres nacionais": 159682.98,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 5746.84,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 8891.27,
    "Outros materiais": 4961.76,
    "Correios": 32800.74
  },
  "Marcelo Crivella": {
    "ID": 3366,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 56797.25,
    "Aquisicao de material de consumo": 489.67,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 40148.84,
    "Contratacao de servicos de apoio ao parlamentar": 34022,
    "Divulgacao da atividade parlamentar": 600,
    "Passagens aereas. aquaticas e terrestres nacionais": 35330.16,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3975.74,
    "Outros materiais": 1348.21,
    "Correios": 17781.27
  },
  "Marta Suplicy": {
    "ID": 5000,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 128558.48,
    "Aquisicao de material de consumo": 761.3,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 4304.71,
    "Contratacao de servicos de apoio ao parlamentar": 35217.35,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 35211.94,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5317.99,
    "Outros materiais": 2134.92,
    "Correios": 5445.36
  },
  "Omar Aziz": {
    "ID": 5525,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 240000,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 12692.88,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3085.03,
    "Outros materiais": 2532.8,
    "Correios": 19443.15
  },
  "Otto Alencar": {
    "ID": 5523,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 34462.38,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 95117.88,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 41941.49,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3298.16,
    "Outros materiais": 2722.72,
    "Correios": 17339.45
  },
  "Pastor Valadares": {
    "ID": 5617,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 12144.9,
    "Aquisicao de material de consumo": 3415,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 15866.65,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 628,
    "Passagens aereas. aquaticas e terrestres nacionais": 24671.12,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 241.5,
    "Outros materiais": 153.22,
    "Correios": 8771.67
  },
  "Paulo Bauer": {
    "ID": 3741,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 156976.95,
    "Aquisicao de material de consumo": 11309.46,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 114603.92,
    "Contratacao de servicos de apoio ao parlamentar": 5562.85,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 73090.83,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 6466.96,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3412.41,
    "Outros materiais": 3436.03,
    "Correios": 50343.42
  },
  "Paulo Paim": {
    "ID": 825,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 37713.35,
    "Aquisicao de material de consumo": 32347.49,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 106879.99,
    "Contratacao de servicos de apoio ao parlamentar": 85447.25,
    "Divulgacao da atividade parlamentar": 38613.9,
    "Passagens aereas. aquaticas e terrestres nacionais": 54664.22,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 7645.52,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6716.78,
    "Outros materiais": 1825.2,
    "Correios": 43930.71
  },
  "Paulo Rocha": {
    "ID": 374,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 105121.48,
    "Aquisicao de material de consumo": 5029.25,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 183406.16,
    "Contratacao de servicos de apoio ao parlamentar": 5500,
    "Divulgacao da atividade parlamentar": 6300,
    "Passagens aereas. aquaticas e terrestres nacionais": 140469.88,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 680.45,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 897.98,
    "Outros materiais": 4482.7,
    "Correios": 96673.34
  },
  "Pedro Chaves": {
    "ID": 5116,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 35920.06,
    "Aquisicao de material de consumo": 23576.14,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 22817.44,
    "Contratacao de servicos de apoio ao parlamentar": 72984.34,
    "Divulgacao da atividade parlamentar": 22160,
    "Passagens aereas. aquaticas e terrestres nacionais": 33129.98,
    "Servicos de Seguranca Privada": 2850,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3545.55,
    "Outros materiais": 2446.85,
    "Correios": 21151.31
  },
  "Pinto Itamaraty": {
    "ID": 4606,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 6510.98,
    "Contratacao de servicos de apoio ao parlamentar": 3500,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 6967.3,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 267.69,
    "Outros materiais": 136.77,
    "Correios": 1498.94
  },
  "Raimundo Lira": {
    "ID": 2207,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 18000,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 124800,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2709.51,
    "Outros materiais": 1788.42,
    "Correios": 1042.43
  },
  "Randolfe Rodrigues": {
    "ID": 5012,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 55702.88,
    "Aquisicao de material de consumo": 4562.1,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 31322.55,
    "Contratacao de servicos de apoio ao parlamentar": 143990.01,
    "Divulgacao da atividade parlamentar": 7435,
    "Passagens aereas. aquaticas e terrestres nacionais": 211411.91,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 7329.2,
    "Outros materiais": 3777.73,
    "Correios": 46903
  },
  "Regina Sousa": {
    "ID": 5182,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 50037.79,
    "Aquisicao de material de consumo": 3507.66,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 111158.24,
    "Contratacao de servicos de apoio ao parlamentar": 7431,
    "Divulgacao da atividade parlamentar": 2100,
    "Passagens aereas. aquaticas e terrestres nacionais": 73146.63,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4480.09,
    "Outros materiais": 3509.65,
    "Correios": 42331.88
  },
  "Reguffe": {
    "ID": 5236,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 0,
    "Outros materiais": 459.07,
    "Correios": 0
  },
  "Renan Calheiros": {
    "ID": 70,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 36759.26,
    "Aquisicao de material de consumo": 414,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 16000,
    "Passagens aereas. aquaticas e terrestres nacionais": 966.07,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 4180.8,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 8398.41,
    "Outros materiais": 3216.84,
    "Correios": 78852.21
  },
  "Ricardo Ferraço": {
    "ID": 635,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 52021.11,
    "Aquisicao de material de consumo": 4443.77,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 53739.12,
    "Contratacao de servicos de apoio ao parlamentar": 820,
    "Divulgacao da atividade parlamentar": 62520,
    "Passagens aereas. aquaticas e terrestres nacionais": 70550.37,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 9322.56,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4155.2,
    "Outros materiais": 3436.52,
    "Correios": 3576.5
  },
  "Roberto Muniz": {
    "ID": 5052,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 45074.24,
    "Aquisicao de material de consumo": 15359.18,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 45349.87,
    "Contratacao de servicos de apoio ao parlamentar": 1816.3,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 42276.5,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 14305.79,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 1490.71,
    "Outros materiais": 1359.98,
    "Correios": 5088.36
  },
  "Roberto Requião": {
    "ID": 72,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 64798.23,
    "Aquisicao de material de consumo": 8799.22,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 52045.41,
    "Contratacao de servicos de apoio ao parlamentar": 22078.65,
    "Divulgacao da atividade parlamentar": 32450,
    "Passagens aereas. aquaticas e terrestres nacionais": 56558.69,
    "Servicos de Seguranca Privada": 104.7,
    "Diarias": 54506.7,
    "Ressarcimento de Passagens": 1838.38,
    "Combustiveis": 7954.44,
    "Outros materiais": 2043.42,
    "Correios": 23297.08
  },
  "Romário": {
    "ID": 5322,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 51012.95,
    "Aquisicao de material de consumo": 28611.5,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 34000,
    "Divulgacao da atividade parlamentar": 73718,
    "Passagens aereas. aquaticas e terrestres nacionais": 91479.42,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4786.03,
    "Outros materiais": 2892.34,
    "Correios": 13128.26
  },
  "Romero Jucá": {
    "ID": 73,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 49009.48,
    "Aquisicao de material de consumo": 46403.58,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 26280.2,
    "Contratacao de servicos de apoio ao parlamentar": 76168.3,
    "Divulgacao da atividade parlamentar": 27000,
    "Passagens aereas. aquaticas e terrestres nacionais": 102127.55,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 7894.59,
    "Outros materiais": 5669.3,
    "Correios": 52540.09
  },
  "Ronaldo Caiado": {
    "ID": 456,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 74412.62,
    "Aquisicao de material de consumo": 36571,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 45484.92,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 34855.06,
    "Servicos de Seguranca Privada": 510.62,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5954.39,
    "Outros materiais": 3356.12,
    "Correios": 6440.97
  },
  "Rose de Freitas": {
    "ID": 2331,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 68580.17,
    "Aquisicao de material de consumo": 4281.36,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 38457.33,
    "Contratacao de servicos de apoio ao parlamentar": 9870.69,
    "Divulgacao da atividade parlamentar": 1750,
    "Passagens aereas. aquaticas e terrestres nacionais": 152458.52,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 7139.59,
    "Outros materiais": 3442.21,
    "Correios": 18398.42
  },
  "Sérgio Petecão": {
    "ID": 4560,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 50838.61,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 100702.76,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 78757.47,
    "Passagens aereas. aquaticas e terrestres nacionais": 50324.51,
    "Servicos de Seguranca Privada": 750,
    "Diarias": 14308.4,
    "Ressarcimento de Passagens": 4335.94,
    "Combustiveis": 5874.35,
    "Outros materiais": 2493.09,
    "Correios": 62587.54
  },
  "Simone Tebet": {
    "ID": 5527,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 56908.41,
    "Aquisicao de material de consumo": 3052.85,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 14762.95,
    "Contratacao de servicos de apoio ao parlamentar": 5000,
    "Divulgacao da atividade parlamentar": 32500,
    "Passagens aereas. aquaticas e terrestres nacionais": 61763.29,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 5022.87,
    "Outros materiais": 3591.44,
    "Correios": 35418.44
  },
  "Tasso Jereissati": {
    "ID": 3396,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 125100,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 30373.99,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3997.32,
    "Outros materiais": 4701.59,
    "Correios": 28425.3
  },
  "Telmário Mota": {
    "ID": 5535,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 37687.13,
    "Aquisicao de material de consumo": 4175.62,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 112272.37,
    "Contratacao de servicos de apoio ao parlamentar": 180756.99,
    "Divulgacao da atividade parlamentar": 13974.5,
    "Passagens aereas. aquaticas e terrestres nacionais": 96683.08,
    "Servicos de Seguranca Privada": 1440,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 6190.68,
    "Outros materiais": 2228.71,
    "Correios": 7580.98
  },
  "Valdir Raupp": {
    "ID": 3372,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 22791.83,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 92362.13,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 152302,
    "Passagens aereas. aquaticas e terrestres nacionais": 83940.03,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 8677.72,
    "Outros materiais": 5768.29,
    "Correios": 8481.57
  },
  "Vanessa Grazziotin": {
    "ID": 558,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 50126.16,
    "Aquisicao de material de consumo": 5248.09,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 120454.15,
    "Contratacao de servicos de apoio ao parlamentar": 24500,
    "Divulgacao da atividade parlamentar": 117852,
    "Passagens aereas. aquaticas e terrestres nacionais": 93856.94,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 24692.76,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 8213.23,
    "Outros materiais": 5209.76,
    "Correios": 10481.3
  },
  "Vicentinho Alves": {
    "ID": 4763,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 13382.36,
    "Aquisicao de material de consumo": 8310,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 203369.14,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 6000,
    "Passagens aereas. aquaticas e terrestres nacionais": 1386,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 9801.82,
    "Outros materiais": 6620.26,
    "Correios": 69104.69
  },
  "Virginio de Carvalho": {
    "ID": 4786,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 0,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 0,
    "Contratacao de servicos de apoio ao parlamentar": 0,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 1980.7,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 251.53,
    "Outros materiais": 92.39,
    "Correios": 0
  },
  "Waldemir Moka": {
    "ID": 1176,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 55259.31,
    "Aquisicao de material de consumo": 15691.63,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 53921.31,
    "Contratacao de servicos de apoio ao parlamentar": 12340,
    "Divulgacao da atividade parlamentar": 18480,
    "Passagens aereas. aquaticas e terrestres nacionais": 78071.51,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2952.56,
    "Outros materiais": 4465.21,
    "Correios": 25259.08
  },
  "Wellington Fagundes": {
    "ID": 1173,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 107576.4,
    "Aquisicao de material de consumo": 16792.76,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 73854.56,
    "Contratacao de servicos de apoio ao parlamentar": 22504.15,
    "Divulgacao da atividade parlamentar": 3740,
    "Passagens aereas. aquaticas e terrestres nacionais": 50612.24,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 16075.62,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 4849.13,
    "Outros materiais": 3796.45,
    "Correios": 34017.69
  },
  "Wilder Morais": {
    "ID": 5070,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 64745.75,
    "Aquisicao de material de consumo": 38489.61,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 84105.95,
    "Contratacao de servicos de apoio ao parlamentar": 754,
    "Divulgacao da atividade parlamentar": 15617,
    "Passagens aereas. aquaticas e terrestres nacionais": 0,
    "Servicos de Seguranca Privada": 1200,
    "Diarias": 9609.6,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 3387.04,
    "Outros materiais": 3849.29,
    "Correios": 5083.21
  },
  "Zeze Perrella": {
    "ID": 5144,
    "Ano": 2016,
    "Aluguel de imoveis para escritorio politico": 55921.61,
    "Aquisicao de material de consumo": 0,
    "Locomocao. hospedagem. alimentacao. combustiveis e": 37091.97,
    "Contratacao de servicos de apoio ao parlamentar": 49000,
    "Divulgacao da atividade parlamentar": 0,
    "Passagens aereas. aquaticas e terrestres nacionais": 32053.27,
    "Servicos de Seguranca Privada": 0,
    "Diarias": 0,
    "Ressarcimento de Passagens": 0,
    "Combustiveis": 2104.33,
    "Outros materiais": 2017.41,
    "Correios": 118123.57
  }
}
